export * from "./types.js";
export { parseDoc, serializeDoc, hasNonEmptyType } from "./frontmatter.js";
export { Bundle, BundleError, replaceSection } from "./bundle.js";
export { regenerateIndex, regenerateIndexChain } from "./indexer.js";
export type { DirSummary, IndexCache } from "./indexer.js";
export { appendLog, readLog, projectLog, parseLegacyLog } from "./logger.js";
export { appendEvent, readEvents, backfillEventsFromLog } from "./events.js";
export type { KnowledgeEvent, EventFilter } from "./events.js";
export { searchBundle, listTypes, type SearchOptions } from "./search.js";
export { validateBundle } from "./validate.js";
export { lintBundle } from "./lint.js";
export type { LintReport, LintFinding, LintWarning, BrokenLink } from "./lint.js";
export { buildGraph, scanGraph } from "./graph.js";
export type { GraphData, GraphNode, GraphEdge } from "./graph.js";
export { KnowledgeBase, type KnowledgeBaseOptions, type MutationMeta } from "./knowledge-base.js";
